name: Build resemiclip

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-24.04
    container: debian:11-slim

    steps:
      - name: Install dependencies
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install -y gcc-multilib g++-multilib build-essential libc6-dev libc6-dev-i386 git cmake

      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x version/appversion.sh
          rm -rf build && CC=gcc CXX=g++ cmake -B build && cmake --build build -j8

      - name: Prepare files
        run: |
          mkdir -p publish/addons/resemiclip
          cp -r dist/* publish/addons/resemiclip/
          mv build/resemiclip_mm_i386.so publish/addons/resemiclip/resemiclip_mm_i386.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux32
          path: publish/*
